# Версия Node.js
FROM node:22.15.0

# Рабочая дирректория внутри контейнера Backend-части продукта Docker Compose
WORKDIR /nestbackend_kubagame_workspace/nx-workspace/

# Копируем все файлы у которых наименование начинается на "package" и заканчивается типом файла ".json"
COPY ./nx-workspace/package.json          ./package.json
COPY ./nx-workspace/package-lock.json     ./package-lock.json
COPY ./nx-workspace/.npmrc                ./.npmrc

# Устанавливаем NPM зависимости для работы Backend-части продукта
RUN npm install --verbose

# Копируем все остальные файлы
COPY ./nx-workspace/ ./

# # Объявляем порт 3000 доступным для открытия внутри контейнера Backend-части продукта Docker Compose
EXPOSE 3000

# # Запускаем Backend-часть продукта внутри контейнера Docker Compose в режиме разработки и слежки за изменением файлов с кодом
CMD ["sh", "-c", "npm run backend:watch"]
